### ISSUE TITLE
Problema desplegando contratos

### ISSUE THREAD

**Issue by jijaen** [alastria/alastria-identity#11]
Hola,
He instalado un nodo regular sobre el cual queremos desplegar los contratos ubicados en la rama `feature/Registry`.  Para ello se ha configurado el fichero **truffle.js** de la siguiente manera:

module.exports = {
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "**"
    },
    'alastria': {
      host: "23.102.43.166",
      port: 22000,
      network_id: "*",
      gas: 0xffffff,
      gasPrice: 0x0,
      from: "0x12676c82a5763bff8af44d69965e48adfef5ec39"
    }
  }
};

... donde en **host** he indicado la IP del nodo y en **from** el _address_ del nodo creado. Se han copiado los directorios (y su contenido)  **./contracts** y **./migrations** de dicha rama del repositorio en la raíz del proyecto del nodo.

Tras compilar los contratos con `truffle compile` y desbloquear la cuenta por defecto, inicio el despliegue de los _smart contracts_ con `truffle deploy --network alastria` obteniendo la siguiente salida por consola:

`
Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x2cb71be04605a00377de5bb51f58de6f8a434f00545e131b255d01dec10b6bb6
`
... **y en este punto se queda eternamente, no avanza.**  ¿Alguna idea de lo que puede estar pasando?  He de comentaros que aún no hemos hecho el _pull request_ de este nodo y actualmente no está cogiendo pares ni está sincronizado con la _test-net_.

Muchas gracias.

Un saludo.

**Comment by msalitu** [comment]
Hola,
Aunque este issue es de hace mucho tiempo, ahora puedes probar a desplegar los contratos con la herramienta proporcionada en dev-tools/deployContracts.
Cierro por antigüedad.
Saludos
