### ISSUE TITLE
Configuration setup

### ISSUE THREAD

**Issue by phabos** [alastria/alastria-identity#141]
Hello,

We are using currently the `alastria-identity-lib` in our company for a decentralized identity project.
We have our own alastria node so we had to fork the `alastria-identity` project in order to setup the correct config for the `alastria-identity`.

But, as we worry for future updates of the lib, we want to use the lib as it is (without modifying it).
So, is there a way to overload the config in [contracts > ContractsInfos.md](https://github.com/alastria/alastria-identity/blob/master/contracts/ContractInfo.md) and generate the [contracts > bin](https://github.com/alastria/alastria-identity/tree/master/contracts/bin) wihtout modifying your code directly ?

Thank you
Fabien

**Comment by javaguirre** [comment]
Hello phabos! why did you needed to fork the lib? Is it because of the config file?

**Comment by javaguirre** [comment]
Hi! I don't think there is a way right now, but we're working on a refactor of parts of the current library and we should remove that coupling for sure. So the short answer is no, but maybe in the future we can fix that decission.

**Comment by javaguirre** [comment]
We're also working in a [Python library with a different architecture](https://github.com/Wealize/alastria-identity-lib-py/tree/main/alastria_identity/examples), but still there is some legacy we have to remove and we have to build the documentation.

**Comment by phabos** [comment]
Ok thank you for your reply ! Are you interested in a PR for the improvement of the config overload ?

**Comment by javaguirre** [comment]
Sorry, phabos, didn't see your comment, If you have any ideas, of course! I you think you can improve it, give it a shot! :-)
