### ISSUE TITLE
Evaluar onboarding  de empresas con certificados digitales.

### ISSUE THREAD

**Issue by miguelcalero** [alastria/alastria-identity#55]
COVID19. ONBOARDING CON CERTIFICADOS DIGITALES.
Pensar en certificados digitales como el modelo EIDAS -> generar DID Alastria y onboarding. 
Nota: los certificados modernos son a pesonas en representación de Empresas, cuidado con la privacidad.

Criterios de aceptación:
Tenemos un briefing de evaluación de alternativas y una propuesta de implementación.

**Comment by rodrigo-bit4id** [comment]
@miguelcalero Tengo el documento con una propuesta del planteamiento para el onboarding con certificado. Es una opción que sirve para empresas y ciudadanos con DNIe. Pero estoy un poco perdido respecto a donde subirlo, o si debo referenciarlo desde aquí.

**Comment by miguelcalero** [comment]
Si puedes hacerlo público, pega un enlace de google drive o similar aquí con permisos de lectura y comentarios para todo el que tenga el enlace.

**Comment by rodrigo-bit4id** [comment]
Aquí lo tienes [https://drive.google.com/file/d/1noDnYDh3bXIc2AGw8ksEYZFydpiQnRat/view?usp=sharing](https://drive.google.com/file/d/1noDnYDh3bXIc2AGw8ksEYZFydpiQnRat/view)
