### ISSUE TITLE
Evaluar onboarding  de personas 

### ISSUE THREAD

**Issue by miguelcalero** [alastria/alastria-identity#56]
COVID19 (low?). ONBOARDING CON DNIe
Usar certificados digitales de DNIe para el onboarding de los usarios. O que la empresa haga onboarding del usuario.

Criterios de aceptación:
Briefing de evaluación de alternativas y propuesta de implantación.

**Comment by rodrigo-bit4id** [comment]
Dejo el enlace a un posible planteamiento para el onboarding con DNIe [https://drive.google.com/file/d/1noDnYDh3bXIc2AGw8ksEYZFydpiQnRat/view?usp=sharing](url)

**Comment by rodrigo-bit4id** [comment]
@miguelcalero Yo creo que esta debería pasar también a Review in progress.

**Comment by hinsausti** [comment]
Buenas... llego un poco tarde a este hilo. Simplemente comentaros la posibilidad de usar los servicios de verificación de identidad de NeoCheck facilitados durante la pandemia (https://www.neocheck.es/verificacion-identidad-gratis), y luego ya lo interesante que podría resultar que cada uno de los socios "compitamos" por ofrecer los servicios del módulo tanto en la web como en el wallet, que el usuario final o empresa que provee la solución comercial pueda implementar. Nosotros facilitamos funcionalidad para ambas.

**Comment by VictorNS69** [comment]
Out of Alastria's scope
