### ISSUE TITLE
Evaluar wallets comerciales

### ISSUE THREAD

**Issue by miguelcalero** [alastria/alastria-identity#58]
Queremos saber los wallets comerciales existentes para su uso en el contexto de Alastria DID.

Criterio de aceptación:
Briefing de evaluación de alternativas para su uso en CoVID19.

**Comment by JuanLuisGozaloFdez** [comment]
Primera iteracción: 
KaiTrust (everis) (versión opensource al menos)
ValidateID
Gataca (según Carlos Pastor no van ap poder adaptarlo pero confirmar)
uPort (¿adaptable a la versión AlastriaID?)
Grant Thorton
Vottun

**Comment by jftavira** [comment]
Maria: contacto uPort, Jolocom. Pendiente de reunión con ellos.
Juan Luis: Votum. Se auto-evaluaron en el 70% y sale el 40% por que no usaban flujos de Alastria. Están haciendo modificaciones para hacerlo funcionar. 
María propone reunión general de wallets para socios y no socios. Juan Luis, anuncio en la asamblea y agendar la semana del 29, por ejemplo. Dos reuniones: una con los que tienen wallets y otra con Issuers y Service Providers (compatibilidad de credenciales, etc).
