### ISSUE TITLE
Revisar Gobernanza de Smart Contracts

### ISSUE THREAD

**Issue by miguelcalero** [alastria/alastria-identity#62]
COVID19. GOBERNANZA DE SMART CONTRACTS (altas, etc).
Se quiere que el alta de las empresas sea sencilla

Criterio de aceptación:
Propuesta de implementación.

**Comment by jftavira** [comment]
Juan Luis: el jueves 11 se reunión el grupo legal. Se comenzó el debate sobre el problema de la identidad ligado a la gobernanza de la red, está en marcha pero tardará. Juan Luis está preparando pequeño documento para su debate en legal.
