### ISSUE TITLE
Create credentialRegistry proxy

### ISSUE THREAD

**Issue by nefera606** [alastria/alastria-identity#88]
Usando el contrato de storage ya definido, integrar la herencia del contrato proxy de OppenZeppelin para convertir el storage en proxy de acceso y storage.

Esto aplica al contrato credentialRegistryStorage.

Tareas:
- Renombar como credentialRegistryProxy
- Incluir herencia de proxy de OZ

**Comment by ghost** [comment]
Buenos días, creo que más o menos está esta issue. He revisado todo lo que puede cascar al hacerlo upgradeable, y lo único que he visto es el constructor de la librería Ownable. Por tanto, lo que he hecho es cambiarlos por los de la librería compatible con upgrades "openzeppelin-contracts-ethereum-package" y modificar para que estén en la misma versión de solidity que el resto (6.4). Con eso se debería de poder desplegar usando, por ejemplo, el cli de openzeppelin sin ningún problema.

**Comment by ghost** [comment]
En develop había cambios, he revisado AlastriaCredentialRegistry y cambiado el constructor por initialize, la versión estaba correcta 0.5.17 y no tenía herencia ni imports.
