### ISSUE TITLE
Create presentationRegistry proxy

### ISSUE THREAD

**Issue by nefera606** [alastria/alastria-identity#89]
Usando el contrato de storage ya definido, integrar la herencia del contrato proxy de OppenZeppelin para convertir el storage en proxy de acceso y storage.

Esto aplica al contrato presentationRegistryStorage.

Tareas:
- Renombar como presentationRegistryProxy
- Incluir herencia de proxy de OZ

**Comment by alejandroalffer** [comment]
Añadida referencia a SmartContract. Revisión por parte de @nefera606 pendiente

**Comment by Jiang-dxc** [comment]
Buenas Alejandro, me dices la rama donde tengo que revisar esta issue? no lo veo en los merge requests

**Comment by alejandroalffer** [comment]
En la rama develop he revisado AlastriaCredentialRegistry y cambiado el constructor por initialize. Se ha cambiado la versión a 0.5.17 y no tenía herencia ni imports.
